name: Deploy
on:
  push:
    branches:
      - master
jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            jq ".version" --raw-output < lerna.json
  docker-image:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.0'
          service_account_key: ${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}
      - run: gcloud auth configure-docker
      - run: yarn
      - run: (cd packages/server && yarn deploy:image)
  npm-package-api:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: (cd packages/types && yarn build)
      - run: (cd packages/types && npm publish)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  npm-package-authorization:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: (cd packages/authorization && yarn build)
      - run: (cd packages/authorization && npm publish)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
