name: Docker
on:
  pull_request:
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f packages/server/docker/server/Dockerfile -t api-server:latest .
  swr-queue-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f packages/server/docker/swr-queue-worker/Dockerfile -t api-swr-queue-worker:latest .
