name: JavaScript
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn lerna run build
      - run: (cd packages/server && yarn build:server)
      - run: (cd packages/server && yarn build:swr-queue-worker)
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn lint:eslint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn lint:prettier
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn lint:tsc
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn start:redis
      - run: yarn test
  codegen-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: (cd packages/types && yarn codegen)
      - id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
      - run: echo "Outdated types. Please run \`yarn codegen\` in \`packages/types\` and commit your changes." && exit 1
        if: steps.changes.outputs.changed == 1
  codegen-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: (cd packages/server && yarn codegen)
      - id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
      - run: echo "Outdated types. Please run \`yarn codegen\` in \`packages/server\` and commit your changes." && exit 1
        if: steps.changes.outputs.changed == 1
